export const LOAD_PLAYER_DATA = 'LOAD_PLAYER_DATA';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

// Pokemon Actions
export const POKEMON_RELEASED = 'POKEMON_RELEASED';
export const POKEMON_EVOLVED = 'POKEMON_EVOLVED';
